# Generated by Django 2.0.6 on 2018-06-07 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_by',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='for_post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='postable_ptr',
        ),
        migrations.RemoveField(
            model_name='post',
            name='postable_ptr',
        ),
        migrations.RemoveField(
            model_name='post',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Postable',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
