version: '3'

services:
  db:
    image: 'mysql:5.7'
    expose:
      - '3306'
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ticokene20
      MYSQL_PASSWORD: ticoeken20
      MYSQL_DATABASE: db_django
    
  web:
    build: .
    
    command: python3 manage.py runserver 0.0.0.0:8000
    
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8082:80
